server:
  port: 3377

## 方式一：默认配置
#spring:
#  profiles:
#    # 通过激活的配置文件，激活${spring.application.name}-${spring.profiles.active}.yaml的配置
#    # 此配置下使用的是默认命名空间public和默认分组DEFAULT_GROUP
#    active: test

## 方式二：通过Group区分环境
#spring:
#  profiles:
#    # 需要在bootstrap.yaml中配置spring.cloud.nacos.config.group: PROD_GROUP
#    # 且在创建Nacos配置时，需要指定分组为PROD_GROUP
#    active: prod

# 方式三：通过命名空间区分环境
spring:
  profiles:
    # 需要在Nacos中新建命名空间Prod_Namespace
    # 且在bootstrap.yaml中配置spring.cloud.nacos.config.namespace: Prod_Namespace
    active: prod